name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '破壊的変更'
    labels:
      - '破壊的変更'
  - title: '機能追加・改修'
    labels:
      - '機能追加・改修'
  - title: 'Spec'
    labels:
      - 'Spec'
  - title: '修正'
    labels:
      - '修正'
  - title: 'Dependencies'
    labels:
      - 'dependencies'
  - title: 'リファクタリング'
    labels:
      - 'リファクタリング'
  - title: 'CI'
    labels:
      - 'CI'
  - title: 'ドキュメント'
    labels:
      - 'ドキュメント'
  - title: '軽微な変更'
    labels:
      - '軽微な変更'
  - title: 'Docker'
    labels:
      - 'Docker'
  - title: 'AWS'
    labels:
      - 'AWS'
  - title: 'GCP'
    labels:
      - 'GCP'
  - title: '導入'
    labels:
      - '導入'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  $CHANGES
