name: Cypress
on:
  - push
  - workflow_dispatch
jobs:
  main:
    name: Cypress
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Cypress の実行に必要なパッケージをインストールする
        run: |
          lib/github_actions_scripts/install_packages_for_cypress.sh
      - name: Firefox をインストールする
        run: |
          lib/github_actions_scripts/install_firefox.sh
          # lib/github_actions_scripts/install_microsoft_edge.sh
      - uses: actions/cache@v2.1.6
        with:
          path: .cache/yarn
          key: ${{ runner.os }}-yarn-cache-cache-yarn-v1
      - uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-cache-node-modules-v1
      - name: $ yarn install
        run: |
          yarn install
      - name: Cypress を実行する
        run: |
          npx cypress run --parallel --browser firefox --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
