on:
  - push
  - workflow_dispatch
name: Cypress
jobs:
  main:
    name: Cypress
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cypress の実行に必要なパッケージをインストールする
        run: |
          lib/github_actions_scripts/install_packages_for_cypress.sh
      - name: Firefox をインストールする
        run: |
          lib/github_actions_scripts/install_firefox.sh
          # lib/github_actions_scripts/install_microsoft_edge.sh
      - name: Cypress を実行する
        run: |
          npx cypress run --browser firefox --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
