name: Cypress
on:
  - push
  - workflow_dispatch
env:
  YARN_CACHE_FOLDER: .cache/yarn

jobs:
  main:
    name: Cypress
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cypress の実行に必要なパッケージをインストールする
        run: |
          lib/github_actions_scripts/install_packages_for_cypress.sh
      - name: Firefox をインストールする
        run: |
          lib/github_actions_scripts/install_firefox.sh
          # lib/github_actions_scripts/install_microsoft_edge.sh
      - uses: actions/cache@v2.1.6
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1
      - name: $ yarn install
        run: |
          yarn install
      - name: Cypress を実行する
        run: |
          npx cypress run --browser firefox --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
