name: PR Labeler

on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    name: PR Labeler
    runs-on: ubuntu-22.04
    # runs-on: self-hosted
    steps:
      # https://github.com/TimonVS/pr-labeler-action
      - uses: TimonVS/pr-labeler-action@v4.1.1
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
