name: GitHub Container Registry にイメージをプッシュする
on:
  push:
    # タグ付けがなされたときだけ push する（そうしないと set_docker_tag_variable でタグ名が取得できない）
    tags:
      - 'v*.*.*'
env:
  TZ: '/usr/share/zoneinfo/Asia/Tokyo'
  IMAGE_NAME: pixhost_downloader
jobs:
  build_and_push:
    name: Docker のイメージをビルドして GitHub Container Registry にプッシュする
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: QEMU のセットアップ（マルチアーキテクチャビルド用）
        uses: docker/setup-qemu-action@v3.0.0
      - name: Buildx のセットアップ（マルチアーキテクチャビルド用）
        uses: docker/setup-buildx-action@v3.1.0
      - name: Git のタグ名 (vX.Y.Z) を Docker 用のタグ名 (X.Y.Z) に変換して変数に保存する
        id: set_docker_tag_variable
        run: |
          GIT_TAG=$(git tag --sort=-creatordate | sed -n 1p)
          DOCKER_TAG="${GIT_TAG//v/}"
          echo "::set-output name=docker_tag::${DOCKER_TAG}"
      - name: GitHub Container Registry にログインする
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub Actions が act で実行されているかどうかの確認
        id: check_on_act_or_not
        # /opt/hostedtoolcache は act のイメージにしか存在しないことを前提としている
        run: |
          OPT_DIRECTORY_LIST=$(/bin/ls /opt)
          if [[ "$OPT_DIRECTORY_LIST" =~ hostedtoolcache ]]; then IS_EXECUTION_ON_ACT="TRUE"; else IS_EXECUTION_ON_ACT="FALSE"; fi

          echo "::set-output name=is_execution_on_act::${IS_EXECUTION_ON_ACT}"
      - name: イメージをビルドして GitHub Container Registry にプッシュする
        if: ${{ steps.check_on_act_or_not.outputs.is_execution_on_act != 'TRUE' }} # act でローカル実行した場合は push しない
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.set_docker_tag_variable.outputs.docker_tag }}
      - name: CI 成功時に実行される Step
        if: success()
        run: |
          echo '[LOG] Docker イメージ のプッシュに成功しました'
      - name: CI 失敗時に実行される Step
        if: failure()
        run: |
          echo '[LOG] Docker イメージ のプッシュに失敗しました'
