name: Release Drafter

on:
  push:
    branches:
      - development

jobs:
  update_release_draft:
    runs-on: ubuntu-24.04
    # runs-on: self-hosted
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
